# Generated by Django 4.0.3 on 2022-03-24 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fname', models.CharField(max_length=15, verbose_name='FirstName')),
                ('lname', models.CharField(blank=True, max_length=15, verbose_name='LastName')),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Email')),
                ('dob', models.DateField(verbose_name='DOB')),
                ('is_staff', models.BooleanField(default=False, verbose_name='IsStaff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='IsSuperUser')),
                ('password', models.CharField(max_length=16, verbose_name='Password')),
                ('profile', models.ImageField(upload_to='profile/', verbose_name='ProfileImage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterFormModel',
            fields=[
                ('fname', models.CharField(max_length=15, verbose_name='FirstName')),
                ('lname', models.CharField(blank=True, max_length=15, verbose_name='LastName')),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Email')),
                ('dob', models.DateField(verbose_name='DOB')),
                ('password', models.CharField(max_length=16, verbose_name='Password')),
                ('profile', models.ImageField(upload_to='profile/', verbose_name='ProfileImage')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('dateTime', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
                ('image', models.ImageField(upload_to='bolgImages/<django.db.models.fields.related.ForeignKey>/', verbose_name='BlogImage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
