# Generated by Django 4.0.3 on 2022-03-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_id_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='NoOfLikes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
    ]
