# Generated by Django 4.0.4 on 2022-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_customuser_permanent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permanent_address',
            field=models.TextField(default='no address', verbose_name='address'),
        ),
    ]
