# Generated by Django 4.0.4 on 2022-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_and_subjects',
            name='picture',
            field=models.TextField(default='', verbose_name='bannerpic'),
        ),
    ]
