# Generated by Django 4.0.3 on 2022-03-30 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='folowersModel',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowdByModel',
            fields=[
                ('email', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('follwedBy', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
