# Generated by Django 4.0.4 on 2022-05-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_classes_and_subjects_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditmes',
            name='noOfItems',
            field=models.IntegerField(default=0),
        ),
    ]
