# Generated by Django 4.0.3 on 2022-03-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_folowersmodel_followdbymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followdbymodel',
            name='email',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
