# Generated by Django 4.0.3 on 2022-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_classes_and_subjects_classtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes_and_subjects',
            name='subject',
        ),
        migrations.AddField(
            model_name='classes_and_subjects',
            name='subject',
            field=models.ManyToManyField(to='blog.subjects'),
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='viedo_lectures',
        ),
        migrations.AddField(
            model_name='subjects',
            name='viedo_lectures',
            field=models.ManyToManyField(to='blog.viedo_lectures'),
        ),
    ]
