# Generated by Django 4.0.3 on 2022-04-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_classes_and_subjects_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viedo_lectures',
            name='title',
            field=models.CharField(default='No Title', max_length=100),
        ),
    ]
