# Generated by Django 4.0.3 on 2022-04-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_viedo_lectures_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes_and_subjects',
            name='picture',
            field=models.ImageField(default='', upload_to='banners/', verbose_name='bannerpic'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='picture',
            field=models.ImageField(default='', upload_to='banner/', verbose_name='bannerpic'),
        ),
    ]
