# Generated by Django 4.0.3 on 2022-04-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_classes_and_subjects_picture_subjects_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='picture',
        ),
        migrations.AddField(
            model_name='subjects',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
