# Generated by Django 4.0.3 on 2022-04-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_ordereditmes_buyer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='classtype',
            field=models.CharField(default='', max_length=50),
        ),
    ]
