# Generated by Django 4.0.4 on 2022-05-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_storeitems_classtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditmes',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordereditmes',
            name='seller',
        ),
    ]
