# Generated by Django 4.0.4 on 2022-05-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_ordereditmes_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditmes',
            name='address',
            field=models.TextField(default='No Address Given'),
        ),
    ]
